import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut } from "next-auth/react";
import { api, type RouterOutputs } from "../lib/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Atkins tRPC Turbo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Atkins tRPC Turbo</h1>
          <AuthShowcase />
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: session } = api.auth.getSession.useQuery();

  const { data: secretMessage } = api.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: !!session?.user },
  );

  return (
    <div>
      {session?.user && (
        <p>
          {session && (
            <span>
              Logged in as {session?.user?.name} - {session?.user.email}
            </span>
          )}
          {secretMessage && <span> - {secretMessage}</span>}
        </p>
      )}
      <button onClick={session ? () => signOut() : () => signIn()}>
        {session ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
